# Netlify configuration for DAMP Smart Drinkware

[build]
  # Since we're using a static site, no build command needed
  command = ""
  # Publish the website folder
  publish = "website"
  
[build.environment]
  # Node version (if needed for future build processes)
  NODE_VERSION = "18"

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Special caching for HTML files (shorter cache)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# CSS and JS files (longer cache with versioning)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# 404 page redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling for contact forms (if you add them later)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true